### ISSUE TITLE
Allow Svelte 5 as a peer dependency

### ISSUE THREAD

**Issue by Mtn-View** [crocotoast/svelte-virtual-list-ts#2]
I tested this in a Svelte 5 project of mine, and it seems like it works, just needs to have version 5 as an option for the Svelte peer dependency

**Comment by crocotoast** [comment]
Hi, sorry I'm not really working on this library anymore because i dont have much time and dont work with svelte primarily anymore. Im merging the occasional PR but I dont develop any new features or something like that, just FYI. 

If someone wants to take this repo over I'd be happy to do so :)

**Comment by crocotoast** [comment]
Just published a version with the peer dep updated :)
